/**
 * Regenerates docs/HOMEWORK.md from lesson-homework.ts and study-lessons.ts.
 *
 *   npx tsx scripts/generate-homework-md.ts
 *
 * Run after editing any homework spec or lesson title — keeps docs in sync.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { HOMEWORK_BY_SLUG } from "../src/content/lesson-homework";
import { ALL_LESSONS } from "../src/content/study-lessons";
import { MODULES } from "../src/content/study-modules";
import type { LessonHomework } from "../src/types/study";

const OUT_PATH = path.resolve(__dirname, "../docs/HOMEWORK.md");

/** Markdown-escape a cell so pipes inside descriptions don't break the table. */
function cell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function table(hw: LessonHomework): string {
  const headers = ["Уровень", "Название", "Что нужно сделать"];
  const rows: string[][] = hw.levels.map((l) =>
    [l.level, l.title, l.description].map(cell),
  );
  const widths = headers.map((h, i) =>
    Math.max(h.length, ...rows.map((r) => (r[i] ?? "").length)),
  );
  const fmt = (cells: string[]) =>
    "| " + cells.map((c, i) => c.padEnd(widths[i] ?? 0)).join(" | ") + " |";
  const sep =
    "| " + widths.map((w) => "-".repeat(Math.max(3, w))).join(" | ") + " |";
  return [fmt(headers), sep, ...rows.map(fmt)].join("\n");
}

function lessonBlock(slug: string, title: string, suffix?: string): string {
  const hw = HOMEWORK_BY_SLUG[slug];
  if (!hw) {
    return [
      `### ${title}${suffix ? ` ${suffix}` : ""}`,
      "",
      "> Этот урок не использует общую таблицу домашек: задание описано прямо на шаге сдачи в самом уроке. См. [`src/content/study-lessons.ts`](../src/content/study-lessons.ts).",
    ].join("\n");
  }
  const placeholder = hw.urlPlaceholder
    ? `\n**Куда сдавать:** ${hw.urlPlaceholder}.\n`
    : "";
  return [`### ${title}${suffix ? ` ${suffix}` : ""}`, placeholder, table(hw)].join(
    "\n",
  );
}

function main() {
  const lines: string[] = [
    "<!-- Auto-generated by scripts/generate-homework-md.ts. Do not edit by hand — re-run the script after changing lesson-homework.ts. -->",
    "",
    "# Домашние задания всех модулей",
    "",
    "Источник: [`src/content/lesson-homework.ts`](../src/content/lesson-homework.ts).",
    "Каждое задание сдаётся на странице `/study/{slug}/homework`. После одобрения куратором следующий урок открывается автоматически.",
    "",
    "> Если урок открыт без домашки — используй ручную разблокировку в админке (страница группы или ученика, кнопка «Открыть уроки до…»).",
    "",
    "---",
    "",
  ];

  // Module order: AI Creator (1) → AI Student (2) → Vibecoding (3).
  const moduleOrder = ["ai-creator", "ai-student", "vibecoding"] as const;
  const moduleIdx = (slug: string) => moduleOrder.indexOf(slug as typeof moduleOrder[number]);

  for (const m of [...MODULES].sort((a, b) => moduleIdx(a.slug) - moduleIdx(b.slug))) {
    if (moduleIdx(m.slug) < 0) continue;
    lines.push(`## Модуль ${moduleIdx(m.slug) + 1} — ${m.title}`);
    lines.push("");
    lines.push(`> ${m.subtitle}`);
    lines.push("");

    const lessons = ALL_LESSONS.filter((l) => l.module === m.slug).sort(
      (a, b) => a.id - b.id,
    );
    for (const l of lessons) {
      const tierSuffix = l.tier ? ` _(${l.tier}-трек)_` : undefined;
      lines.push(lessonBlock(l.slug, l.title, tierSuffix));
      lines.push("");
    }
    lines.push("---");
    lines.push("");
  }

  // Trim trailing separator block + blank lines.
  while (lines.length > 0 && (lines[lines.length - 1] === "" || lines[lines.length - 1] === "---")) {
    lines.pop();
  }
  lines.push("");

  fs.writeFileSync(OUT_PATH, lines.join("\n"), "utf8");
  console.log(`✓ wrote ${OUT_PATH} (${lines.length} lines)`);
}

main();
